// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.PredatorBG.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(PredatorBGDbContext))]
    partial class PredatorBGDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Imagepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PredatorGameId4")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredatorGameId4");

                    b.ToTable("Cards");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Card");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enums.DSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DamageId")
                        .HasColumnType("int");

                    b.Property<int>("Skill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DamageId");

                    b.ToTable("DSkill");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enums.ESkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EnemyId")
                        .HasColumnType("int");

                    b.Property<int>("Skill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId");

                    b.ToTable("ESkill");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enums.ETeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ETeam");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enums.PChar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Character")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PChar");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enums.PClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PClass");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enums.PSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PlayableId")
                        .HasColumnType("int");

                    b.Property<int>("Skill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayableId");

                    b.ToTable("PSkill");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enums.PTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PTeam");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LobbyGameId")
                        .HasColumnType("int");

                    b.Property<int>("Movie")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayersNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LobbyGameId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imagepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Avoid")
                        .HasColumnType("int");

                    b.Property<int>("Convert")
                        .HasColumnType("int");

                    b.Property<bool>("Coordinated")
                        .HasColumnType("bit");

                    b.Property<int>("CurAtt")
                        .HasColumnType("int");

                    b.Property<int>("CurRec")
                        .HasColumnType("int");

                    b.Property<int>("Free")
                        .HasColumnType("int");

                    b.Property<int>("GotCoord")
                        .HasColumnType("int");

                    b.Property<int>("Heal")
                        .HasColumnType("int");

                    b.Property<int>("HealMin")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Imagepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kill")
                        .HasColumnType("int");

                    b.Property<int>("MarkNum")
                        .HasColumnType("int");

                    b.Property<bool>("OnTurn")
                        .HasColumnType("bit");

                    b.Property<int?>("PredatorGameId")
                        .HasColumnType("int");

                    b.Property<int>("Scan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredatorGameId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.PredatorGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ActivePlayer")
                        .HasColumnType("int");

                    b.Property<int>("FreeRound")
                        .HasColumnType("int");

                    b.Property<int?>("GraveyardId")
                        .HasColumnType("int");

                    b.Property<int?>("HillsId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int?>("RiverId")
                        .HasColumnType("int");

                    b.Property<int?>("RuinsId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialMissed")
                        .HasColumnType("int");

                    b.Property<int>("SpecialValue")
                        .HasColumnType("int");

                    b.Property<int?>("UndergroundId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GraveyardId");

                    b.HasIndex("HillsId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RiverId");

                    b.HasIndex("RuinsId");

                    b.HasIndex("UndergroundId");

                    b.ToTable("PredatorGame");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Damage", b =>
                {
                    b.HasBaseType("WebAPI.PredatorBG.Models.Card");

                    b.Property<int>("Dmg")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PredatorGameId")
                        .HasColumnType("int");

                    b.Property<int?>("PredatorGameId1")
                        .HasColumnType("int");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PredatorGameId");

                    b.HasIndex("PredatorGameId1");

                    b.HasDiscriminator().HasValue("Damage");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enemy", b =>
                {
                    b.HasBaseType("WebAPI.PredatorBG.Models.Card");

                    b.Property<bool>("FaceDown")
                        .HasColumnType("bit");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int?>("PredatorGameId")
                        .HasColumnType("int")
                        .HasColumnName("Enemy_PredatorGameId");

                    b.Property<int?>("PredatorGameId1")
                        .HasColumnType("int")
                        .HasColumnName("Enemy_PredatorGameId1");

                    b.Property<int?>("PredatorGameId2")
                        .HasColumnType("int");

                    b.Property<int?>("PredatorGameId3")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasIndex("PredatorGameId");

                    b.HasIndex("PredatorGameId1");

                    b.HasIndex("PredatorGameId2");

                    b.HasIndex("PredatorGameId3");

                    b.HasIndex("TeamId");

                    b.HasDiscriminator().HasValue("Enemy");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Playable", b =>
                {
                    b.HasBaseType("WebAPI.PredatorBG.Models.Card");

                    b.Property<bool>("Activated")
                        .HasColumnType("bit");

                    b.Property<int>("AttPoint")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateBy")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("Playable_PlayerId");

                    b.Property<int?>("PlayerId1")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId2")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId3")
                        .HasColumnType("int");

                    b.Property<int?>("PredatorGameId")
                        .HasColumnType("int")
                        .HasColumnName("Playable_PredatorGameId");

                    b.Property<int?>("PredatorGameId1")
                        .HasColumnType("int")
                        .HasColumnName("Playable_PredatorGameId1");

                    b.Property<int?>("PredatorGameId2")
                        .HasColumnType("int")
                        .HasColumnName("Playable_PredatorGameId2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RecPoint")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("Playable_TeamId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ClassId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId1");

                    b.HasIndex("PlayerId2");

                    b.HasIndex("PlayerId3");

                    b.HasIndex("PredatorGameId");

                    b.HasIndex("PredatorGameId1");

                    b.HasIndex("PredatorGameId2");

                    b.HasIndex("TeamId");

                    b.HasDiscriminator().HasValue("Playable");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.PredatorBG.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Card", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("ObjectiveDeck")
                        .HasForeignKey("PredatorGameId4");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enums.DSkill", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.Damage", null)
                        .WithMany("Skills")
                        .HasForeignKey("DamageId");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enums.ESkill", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.Enemy", null)
                        .WithMany("Skills")
                        .HasForeignKey("EnemyId");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enums.PSkill", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.Playable", null)
                        .WithMany("Skills")
                        .HasForeignKey("PlayableId");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Lobby", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", "LobbyGame")
                        .WithMany()
                        .HasForeignKey("LobbyGameId");

                    b.Navigation("LobbyGame");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Player", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("Players")
                        .HasForeignKey("PredatorGameId");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.PredatorGame", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.Enemy", "Graveyard")
                        .WithMany()
                        .HasForeignKey("GraveyardId");

                    b.HasOne("WebAPI.PredatorBG.Models.Enemy", "Hills")
                        .WithMany()
                        .HasForeignKey("HillsId");

                    b.HasOne("WebAPI.PredatorBG.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("WebAPI.PredatorBG.Models.Enemy", "River")
                        .WithMany()
                        .HasForeignKey("RiverId");

                    b.HasOne("WebAPI.PredatorBG.Models.Enemy", "Ruins")
                        .WithMany()
                        .HasForeignKey("RuinsId");

                    b.HasOne("WebAPI.PredatorBG.Models.Enemy", "Underground")
                        .WithMany()
                        .HasForeignKey("UndergroundId");

                    b.Navigation("Graveyard");

                    b.Navigation("Hills");

                    b.Navigation("Location");

                    b.Navigation("River");

                    b.Navigation("Ruins");

                    b.Navigation("Underground");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Damage", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.Player", null)
                        .WithMany("Injuries")
                        .HasForeignKey("PlayerId");

                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("DamageDeck")
                        .HasForeignKey("PredatorGameId");

                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("UsedDamageDeck")
                        .HasForeignKey("PredatorGameId1");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enemy", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("CombatEnemies")
                        .HasForeignKey("PredatorGameId");

                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("DeadEnemies")
                        .HasForeignKey("PredatorGameId1");

                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("EnemyDeck")
                        .HasForeignKey("PredatorGameId2");

                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("Operations")
                        .HasForeignKey("PredatorGameId3");

                    b.HasOne("WebAPI.PredatorBG.Models.Enums.ETeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Playable", b =>
                {
                    b.HasOne("WebAPI.PredatorBG.Models.Enums.PChar", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId");

                    b.HasOne("WebAPI.PredatorBG.Models.Enums.PClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("WebAPI.PredatorBG.Models.Player", null)
                        .WithMany("ActiveCards")
                        .HasForeignKey("PlayerId");

                    b.HasOne("WebAPI.PredatorBG.Models.Player", null)
                        .WithMany("DisposeDeck")
                        .HasForeignKey("PlayerId1");

                    b.HasOne("WebAPI.PredatorBG.Models.Player", null)
                        .WithMany("DrawDeck")
                        .HasForeignKey("PlayerId2");

                    b.HasOne("WebAPI.PredatorBG.Models.Player", null)
                        .WithMany("Hand")
                        .HasForeignKey("PlayerId3");

                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("Barrack")
                        .HasForeignKey("PredatorGameId");

                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("CommanderDeck")
                        .HasForeignKey("PredatorGameId1");

                    b.HasOne("WebAPI.PredatorBG.Models.PredatorGame", null)
                        .WithMany("HQDeck")
                        .HasForeignKey("PredatorGameId2");

                    b.HasOne("WebAPI.PredatorBG.Models.Enums.PTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Character");

                    b.Navigation("Class");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Player", b =>
                {
                    b.Navigation("ActiveCards");

                    b.Navigation("DisposeDeck");

                    b.Navigation("DrawDeck");

                    b.Navigation("Hand");

                    b.Navigation("Injuries");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.PredatorGame", b =>
                {
                    b.Navigation("Barrack");

                    b.Navigation("CombatEnemies");

                    b.Navigation("CommanderDeck");

                    b.Navigation("DamageDeck");

                    b.Navigation("DeadEnemies");

                    b.Navigation("EnemyDeck");

                    b.Navigation("HQDeck");

                    b.Navigation("ObjectiveDeck");

                    b.Navigation("Operations");

                    b.Navigation("Players");

                    b.Navigation("UsedDamageDeck");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Damage", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Enemy", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("WebAPI.PredatorBG.Models.Playable", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
